workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    environment:
      android_signing:
        - taskmapperKey
        # Never push key directly without encryption
      groups:
        - google_play
      vars:
        PACKAGE_NAME: 'com.reactnativecli'
      node: latest
    artifacts:
      - android/app/build/outputs/**/*.apk
